function J_Def = SLAM_Define_Jacobain( )

    global PreIntegration_options
    
    dUv_dAbgxyz_Def = struct ( ...
            'val', zeros(2, 6), ...
            'row', [], ...
            'col', [] ...
            );

    dUv_dFxyz_Def = struct ( ...
            'val', zeros(2, 3), ...
            'row', [], ...
            'col', [] ...
            );

    dUv_dATu2c_Def = struct ( ...
            'val', zeros(2, 6), ...
            'row', [], ...
            'col', [] ...
            );

    dUv_dX_Def = struct ( ...
            'dAbgxyz_1',    dUv_dAbgxyz_Def, ...
            'dFxyz',        dUv_dFxyz_Def, ...
            'dATu2c',        dUv_dATu2c_Def ...
            );

    if ( PreIntegration_options.bPreInt == 1 )                
        dDp_dAbg_Def = struct ( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );
        
        dDp_dTrans_Def = struct ( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );
        
        dDp_dV_Def = struct ( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );
            
        dDp_dG_Def = struct ( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );
        
        dDp_dBf_Def = struct ( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );

        dDp_dBw_Def = struct ( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );
            
        dDp_dX_Def = struct ( ...
                'dDp_dAbg_1',   dDp_dAbg_Def, ...
                'dDp_dTrans_1', dDp_dTrans_Def, ...
                'dDp_dTrans_2', dDp_dTrans_Def, ...
                'dDp_dV_1',     dDp_dV_Def, ...
                'dDp_dG',       dDp_dG_Def, ...
                'dDp_dBf',      dDp_dBf_Def, ...
                'dDp_dBw',      dDp_dBw_Def ...
                );
        
        dDv_dAbg_Def = struct ( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );
            
        dDv_dV_Def = struct ( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );

        dDv_dG_Def = struct ( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );

        dDv_dBf_Def = struct ( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );

        dDv_dBw_Def = struct ( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );
        
        dDv_dX_Def = struct ( ...
                'dDv_dAbg_1',   dDv_dAbg_Def, ...
                'dDv_dV_1',     dDv_dV_Def, ...
                'dDv_dV_2',     dDv_dV_Def, ...
                'dDv_dG',       dDv_dG_Def, ...
                'dDv_dBf',      dDv_dBf_Def, ...
                'dDv_dBw',      dDv_dBw_Def ...
                );
        
        dDphi_dABG_Def = struct ( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );
        
        dDphi_dBw_Def = struct ( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );
            
        dDphi_dX_Def = struct ( ...
                'dDphi_dAbg_1', dDphi_dABG_Def, ...
                'dDphi_dAbg_2', dDphi_dABG_Def, ...
                'dDphi_dBw',    dDphi_dBw_Def ...
                );
        
        dIntlDelta_dX_Def = struct ( ...
                'dDp_dX',   dDp_dX_Def, ...
                'dDv_dX',   dDv_dX_Def, ...
                'dDphi_dX', dDphi_dX_Def ...
                );        
                
    else % bPreInt == 0
        dW_dPhi_Def = struct ( ...
                'val',  zeros(3, 3), ...
                'row',  [], ...
                'col',  []  ...
                );
                
        dW_dBw_Def = struct ( ...
                'val',  zeros(3, 3), ...
                'row',  [], ...
                'col',  []  ...
                );
                
        dW_dX_Def = struct ( ...
                'dW_dPhi',      dW_dPhi_Def, ...
                'dW_dPhi_1',    dW_dPhi_Def, ...
                'dW_dBw',       dW_dBw_Def ...
                );
              
        dAcc_dPhi_Def = struct ( ...
                'val',  zeros(3, 3), ...
                'row',  [], ...
                'col',  [] ...
                );
                
        dAcc_dV_Def = struct ( ...
                'val',  zeros(3, 3), ...
                'row',  [], ...
                'col',  [] ...
                );
                
        dAcc_dG_Def = struct ( ...
                'val',  zeros(3, 3), ...
                'row',  [], ...
                'col',  [] ...
                );
                
        dAcc_dBf_Def = struct ( ...
                'val',  zeros(3, 3), ...
                'row',  [], ...
                'col',  [] ...
                );
                
        dAcc_dX_Def = struct ( ...
                'dAcc_dPhi',    dAcc_dPhi_Def, ...
                'dAcc_dV',      dAcc_dV_Def, ...
                'dAcc_dV_1',    dAcc_dV_Def, ...
                'dAcc_dG',      dAcc_dG_Def, ...
                'dAcc_dBf',     dAcc_dBf_Def ...
                );
                
        dDeltaT_dT_Def = struct ( ...
                'val',  zeros(3, 3), ...
                'row',  [], ...
                'col',  [] ...
                );
                
        dDeltaT_dV_Def = struct ( ...
                'val',  zeros(3, 3), ...
                'row',  [], ...
                'col',  [] ...
                );
                
        dDeltaT_dX_Def = struct ( ...
                'dDeltaT_dT',   dDeltaT_dT_Def, ...
                'dDeltaT_dT_1', dDeltaT_dT_Def, ...
                'dDeltaT_dV',   dDeltaT_dV_Def ...
                );
                
        dImu_dX_Def = struct ( ...
                'dW_dX',        dW_dX_Def, ...
                'dAcc_dX',      dAcc_dX_Def, ...
                'dDeltaT_dX',   dDeltaT_dX_Def ...
                );
                
    end % bPreInt
    
    dG_dG_Def = struct( ...
            'val', zeros(3, 3), ...
            'row', [], ...
            'col', [] ...
            );
        
    dAu2c_dX_Def = struct( ...
            'val', zeros(3, 3), ...
            'row', [], ...
            'col', [] ...
            );
    
    dTu2c_dX_Def = struct( ...
            'val', zeros(3, 3), ...
            'row', [], ...
            'col', [] ...
            );

    if PreIntegration_options.bVarBias == 0        
        dBf_dX_Def = struct( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );
    
        dBw_dX_Def = struct( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );
    else
        dBf_dX1_Def = struct( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );
    
        dBw_dX1_Def = struct( ...
                'val', zeros(3, 3), ...
                'row', [], ...
                'col', [] ...
                );

        dBf_dX_Def = struct( ...
            'iter', struct( ...
                         'dX1', repmat( dDv_dBf1_Def, 1, 1 ), ... % will grow
                         'dX2', repmat( dDv_dBf1_Def, 1, 1 ) ... % will grow
                    ) ...
            );
        
        dBw_dX_Def = struct( ...
            'iter', struct( ...
                         'dX1', repmat( dDv_dBf1_Def, 1, 1 ), ... % will grow
                         'dX2', repmat( dDv_dBf1_Def, 1, 1 ) ... % will grow
                    ) ...
            );
    end
    
    if ( PreIntegration_options.bPreInt == 1)
        J_Def = struct( ...
                'dUv_dX',           repmat( dUv_dX_Def, 1, 1 ), ... % will expand
                'dIntlDelta_dX',    repmat( dIntlDelta_dX_Def, 1, 1 ), ... % will expand
                'dAu2c_dX',         dAu2c_dX_Def, ...
                'dTu2c_dX',         dTu2c_dX_Def, ...
                'dBf_dX',           dBf_dX_Def, ...
                'dBw_dX',           dBw_dX_Def ...
                );
    else
        J_Def = struct( ...
                'dUv_dX',           repmat( dUv_dX_Def, 1, 1 ), ... % will expand
                'dImu_dX',          repmat( dImu_dX_Def, 1, 1 ), ... % will expand
                'dAu2c_dX',         dAu2c_dX_Def, ...
                'dTu2c_dX',         dTu2c_dX_Def, ...
                'dBf_dX',           dBf_dX_Def, ...
                'dBw_dX',           dBw_dX_Def ...
                );
    end
    
    if ( PreIntegration_options.bAddZg == 1 )
        J_Def.dG_dG = dG_dG_Def;
    end
    